### ISSUE TITLE
Preparing this package

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/RAMEGA#1]
Thank you for letting know about this package - I have some suggestions.

There is no package website, and no actual release seen at https://github.com/vlaver/RAMEGA/releases. 

Furthermore, the metadata in https://github.com/vlaver/RAMEGA/blob/master/PackageInfo.g state that is is located in gap-packages organisation, and not under your personal account. If the plan is to migrate the package there, you're most welcome to do it right now.

Next, I was surprised to see that me and @fingolfin happen to contribute to this repository, but then realised that you most likely imported the repository for the Thelma package and then replaced everything with another package (e.g. 3972a9f649fe50932127b6d987d9fcac54253d2c is a commit that was made in Thelma). This is not a recommended way to start a new project - it makes the history polluted with irrelevant changes. For a new project, the usual way is to call `git init` to initialise the repository, and then `git add` to add files. But since you have already have certain commits on top of the initial import, let's leave it as is for now. 

Also, the `version` file is a relic from some other package. One can organise  a package without it, and it seems that even now RAMEGA is not using it, and it can be removed.
 
Finally, since this package provides a standard test, I suggest to add it to the tests that we offer to GAP package authors to test _development_ versions of their packages for compatibility with GAP stable and master branches:
- https://github.com/gap-infra/gap-docker-pkg-tests-master-devel 
- https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.10-devel
- https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel

The first of these repositories has a README file with further details. To add your package to the test, please submit a pull request to add a line to the `.travis.yml` file.

**Comment by vlaver** [comment]
Thank you for your comments!

> There is no package website, and no actual release seen at https://github.com/vlaver/RAMEGA/releases.

Done: https://vlaver.github.io/RAMEGA/
Release is also published.

> Furthermore, the metadata in https://github.com/vlaver/RAMEGA/blob/master/PackageInfo.g state that is is located in gap-packages organisation, and not under your personal account. If the plan is to migrate the package there, you're most welcome to do it right now.

I would like to, but I need assistance in this. Is there any online help available?

> Also, the `version` file is a relic from some other package. One can organise a package without it, and it seems that even now RAMEGA is not using it, and it can be removed.

I removed this file.
 
> Finally, since this package provides a standard test, I suggest to add it to the tests that we offer to GAP package authors to test _development_ versions of their packages for compatibility with GAP stable and master branches.

Done.

**Comment by olexandr-konovalov** [comment]
Please see about migrating the repository: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by olexandr-konovalov** [comment]
@vlaver alternatively, you can give me admin rights and I will transfer the repository. You will have to update the package metadata then, and also your PR to tests in gap-infra, so to safe time, actually one should have transferred the repository first.

**Comment by olexandr-konovalov** [comment]
tests of this package are not passing cleanly - see e.g.
- https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-master-devel/jobs/676044156
- https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/jobs/675342087

I suggest to finis its migration to gap-packages and then we can set up Travis CI tests there properly. Your repository has `.travis.yml` file but I am not sure if you are actually using it.

**Comment by vlaver** [comment]
> tests of this package are not passing cleanly - see e.g.
> 
>     * https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-master-devel/jobs/676044156
> 
>     * https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/jobs/675342087
> 
> 
> I suggest to finis its migration to gap-packages and then we can set up Travis CI tests there properly. Your repository has `.travis.yml` file but I am not sure if you are actually using it.

I migrated the package. Also, I've added the LAGUNA package to the needed packages list. Hope that this will resolve the issue.

**Comment by olexandr-konovalov** [comment]
@vlaver thanks for migrating. I gave you admin rights for this repository.

**Comment by vlaver** [comment]
> @vlaver thanks for migrating. I gave you admin rights for this repository.

@alex-konovalov , is there anything left in this issue thread that is yet to be done? Can it be closed?

**Comment by olexandr-konovalov** [comment]
Not in this issue - can be closed. Thanks!
