### ISSUE TITLE
GetRandomNormalizedUnitaryUnit in the manual

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/RAMEGA#5]
The manual has two sections for `GetRandomNormalizedUnitaryUnit`, with a different content.

**Comment by vlaver** [comment]
> The manual has two sections for `GetRandomNormalizedUnitaryUnit`, with a different content.

It was done intentionally, as the second section describes the overloaded version for an arbitrary antiautomorphism eta.

**Comment by olexandr-konovalov** [comment]
Thanks for explanation. In this case you can see that e.g. [the index](https://gap-packages.github.io/RAMEGA/doc/chapInd.html) only refers to the 1st mansection. There are better ways of doing this, supported by GAPDoc. One of them is using labels, but in this case labels are not needed - instead, you can document it as `GetRandomNormalizedUnitaryUnit( KG [, eta] )` indicating that the 2nd argument is optional, and document both usages, with examples, in the same mansection. There are surely many cases like this in the GAP manual, if you need to look at a GAPDoc source for this.

**Comment by vlaver** [comment]
> Thanks for explanation. In this case you can see that e.g. [the index](https://gap-packages.github.io/RAMEGA/doc/chapInd.html) only refers to the 1st mansection. There are better ways of doing this, supported by GAPDoc. One of them is using labels, but in this case labels are not needed - instead, you can document it as `GetRandomNormalizedUnitaryUnit( KG [, eta] )` indicating that the 2nd argument is optional, and document both usages, with examples, in the same mansection. There are surely many cases like this in the GAP manual, if you need to look at a GAPDoc source for this.

Dear Alexander, I made the suggested changes in the documentation (namely, I used square brackets for optional parameters).

**Comment by olexandr-konovalov** [comment]
Thanks - 9da5e035aaf6bf3c13c96d26ac68dc3591c4b56d looks good to me.
