### ISSUE TITLE
Inefficiency in BasicGroup

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/RAMEGA#6]
Some notes about the following code:
https://github.com/gap-packages/RAMEGA/blob/c1e2a4dfab15f74fb176d5975da4b39c4372ca9a/lib/random.gi#L25-L35

First, the error will never happen, since the method is installed for `IsGroupRing` and hence method selection will take care f the type of an argument.

Second, do not finish error messages with dot, they may be part of further output in a break loop. Also, this is not a title, so there is no need for capitalisation in "Group Ring".

Third, `Group(List(g,x->x^emb));` will generate a new group using the full list of elements of a group as generators. This is **very** inefficient. One should only take images of generators of `g` and generate a new group by them.

Finally, this method may not be necessary, as the same can be simply done using `Embedding`:
```
gap> G:=DihedralGroup(8);
<pc group of size 8 with 3 generators>
gap> F:=GF(2);
GF(2)
gap> FG:=GroupRing(F,G);
<algebra-with-one over GF(2), with 3 generators>
gap> f:=Embedding(G,FG);
<mapping: Group( [ f1, f2, f3 ] ) -> AlgebraWithOne( GF(2), ... ) >
gap> Image(f);
<group of size 8 with 3 generators>
```

**Comment by vlaver** [comment]
Thank you for your suggestions, I made the corresponding changes to the BasicGroup function.

**Comment by olexandr-konovalov** [comment]
OK (it's useful to keep the commit history and issues/PRs connected and refer to commits in issues or vice versa). So the changes were made in 628a9461a2581cf6423b945b057bba3c65d9252a. Closing this for now then!
