### ISSUE TITLE
Tests need adjustment

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/RAMEGA#7]
You can see commit status at https://github.com/gap-packages/RAMEGA/commits/master - red crosses indicate CI failures. Indeed as you can see at e.g. https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-master-devel/jobs/686852045:

```
########> Diff in /home/gap/RAMEGA/gaproot/pkg/RAMEGA/tst/test-examples.tst:13
# Input is:
BasicGroup(KG);
# Expected output:
<group with 4 generators>
# But found:
<group of size 4 with 1 generators>
########
```

so this example should be updated.

I recommend adding badges to point to Travis and Codecov to the README - then you will see test status easier and navigate to the tests in one click.

**Comment by vlaver** [comment]
I've made the suggested correction: [522f4cb](https://github.com/gap-packages/RAMEGA/commit/522f4cb9c1602e951c3fe12a9614637c70489654). And added the badges: [9dca5f8](https://github.com/gap-packages/RAMEGA/commit/9dca5f89b99961e3eb264ee0b9203688082a1f26)

**Comment by olexandr-konovalov** [comment]
Ok - please see #9 now.

**Comment by olexandr-konovalov** [comment]
Thanks!
