### ISSUE TITLE
Typo in affiliation

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/RAMEGA#8]
https://github.com/gap-packages/RAMEGA/blob/9da5e035aaf6bf3c13c96d26ac68dc3591c4b56d/doc/title.xml#L30

**Comment by vlaver** [comment]
Fixed by [38e706c](https://github.com/gap-packages/RAMEGA/commit/38e706c13099b3ee2cae7a7001d0da32bfbde034)
